apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: artifactory
    component: artifactory
  name: artifactory-docker
  namespace: artifactory
spec:
  port:
    targetPort: http-artifactory
  tls:
    termination: edge
  to:
    kind: Service
    name: jfrog-container-registry-artifactory
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: artifactory
    component: artifactory
  name: artifactory-ui
  namespace: artifactory
spec:
  port:
    targetPort: http-router
  tls:
    termination: edge
  to:
    kind: Service
    name: jfrog-container-registry-artifactory
