apiVersion: v1
kind: Secret
metadata:
  name: tpa-service-cluster-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
    tpa-service-app: "true"
  annotations:
    KChost: "${KEYCLOAK_HOST}"
    redirect1: "${REDIRECT_URI1}"
    redirect2: "${REDIRECT_URI2}"
    redirect3: "${REDIRECT_URI3}"
    redirect4: "${REDIRECT_URI4}"
    AppDomain: "${APP_DOMAIN_URL}"
    OIDCissuer: "${OIDC_ISSUER_URL}"
type: Opaque
stringData:
  name: tpa-service-cluster
  server: "${SERVER_URL}"
  config: |
    {
      "bearerToken": "${BTOKEN}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "${CA_DATA}"
      }
    }

