kind: Secret
apiVersion: v1
metadata:
  name: install-config-template
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  install-config.yaml: YWRkaXRpb25hbFRydXN0QnVuZGxlUG9saWN5OiBQcm94eW9ubHkKYXBpVmVyc2lvbjogdjEKYmFzZURvbWFpbjogVE9fQkVfUkVQTEFDRURfQllfSElWRQpjb21wdXRlOgotIGFyY2hpdGVjdHVyZTogYW1kNjQKICBoeXBlcnRocmVhZGluZzogRW5hYmxlZAogIG5hbWU6IHdvcmtlcgogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICB0eXBlOiBtNmkuMnhsYXJnZQogIHJlcGxpY2FzOiAzCmNvbnRyb2xQbGFuZToKICBhcmNoaXRlY3R1cmU6IGFtZDY0CiAgaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiBtYXN0ZXIKICBwbGF0Zm9ybToge30KICByZXBsaWNhczogMgptZXRhZGF0YToKICBjcmVhdGlvblRpbWVzdGFtcDogbnVsbAogIG5hbWU6IFRPX0JFX1JFUExBQ0VEX0JZX0hJVkUKbmV0d29ya2luZzoKICBjbHVzdGVyTmV0d29yazoKICAtIGNpZHI6IDEwLjEyOC4wLjAvMTQKICAgIGhvc3RQcmVmaXg6IDIzCiAgbWFjaGluZU5ldHdvcms6CiAgLSBjaWRyOiAxMC4wLjAuMC8xNgogIG5ldHdvcmtUeXBlOiBPVk5LdWJlcm5ldGVzCiAgc2VydmljZU5ldHdvcms6CiAgLSAxNzIuMzAuMC4wLzE2CnBsYXRmb3JtOgogIGF3czoKICAgIHJlZ2lvbjogdXMtZWFzdC0xCnB1Ymxpc2g6IEV4dGVybmFsCnB1bGxTZWNyZXQ6IFRPX0JFX1JFUExBQ0VEX0JZX0hJVkUK
type: Opaque

